apiVersion: v1
kind: ConfigMap
metadata:
  name: router-nginx-conf
  namespace: uploadgate
data:
  nginx.conf: |
    worker_processes  1;
    
    events { worker_connections  1024; }
    
    http {
      server_tokens off;
    
      log_format json escape=json
        '{'
          '"ts":"$time_iso8601",'
          '"remote_addr":"$remote_addr",'
          '"method":"$request_method",'
          '"uri":"$request_uri",'
          '"status":$status,'
          '"request_length":$request_length,'
          '"body_bytes_sent":$body_bytes_sent,'
          '"request_time":$request_time,'
          '"upstream_addr":"$upstream_addr",'
          '"upstream_status":"$upstream_status",'
          '"upstream_response_time":"$upstream_response_time",'
          '"request_id":"$request_id",'
          '"user_agent":"$http_user_agent"'
        '}';
    
      access_log /var/log/nginx/access.log json;
      error_log  /var/log/nginx/error.log warn;
    
      client_max_body_size 10m;
      client_body_timeout 30s;
      send_timeout 30s;
    
      limit_req_zone $binary_remote_addr zone=upload_rl:10m rate=5r/s;
      limit_req_status 429;
    
      upstream upload_api {
        server upload-api:5000;
        keepalive 16;
      }
    
      server {
        listen 80;
    
        location = /health {
          default_type text/plain;
          return 200 "ok\n";
        }
    
        location /upload/ {
          limit_req zone=upload_rl burst=20 nodelay;
    
          proxy_http_version 1.1;
          proxy_set_header Connection "";
    
          proxy_set_header Host $host;
          proxy_set_header X-Request-Id $request_id;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    
          proxy_read_timeout 60s;
          proxy_send_timeout 60s;
          proxy_connect_timeout 5s;
    
          proxy_request_buffering off;
          proxy_pass http://upload_api;
        }
    
        location / {
          proxy_http_version 1.1;
          proxy_set_header Connection "";
    
          proxy_set_header Host $host;
          proxy_set_header X-Request-Id $request_id;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    
          proxy_read_timeout 30s;
          proxy_send_timeout 30s;
          proxy_connect_timeout 5s;
    
          proxy_pass http://upload_api;
        }
      }
    }
