uploadApi:
  auth:
    secretName: uploadgate-auth
  image: "uploadgate-upload-api"
  tag: "0.1.0"
  replicas: 1
  port: 5000

router:
  image: "uploadgate-router"
  tag: "0.1.0"
  replicas: 1
  port: 80
  service:
    type: ClusterIP   # NodePort yapmak için: NodePort
    nodePort: 31880   # sadece type=NodePort iken kullanılır
  clientMaxBodySize: "100m"

pvc:
  create: false
  name: uploadgate-pvc
  size: 1Gi
  storageClassName: local-path
